
post_install() {
	# Add 'games' Group
	getent group games > /dev/null || /usr/sbin/groupadd -g 20 games

	echo ">>> In order to use ePSXe, add your user to the 'games' group."
	echo ">>>"
	echo ">>>  # gpasswd -a USERNAME games"
	echo ">>>"
	echo ">>> Remember to logout and log back in for the changes to take effect."
}

post_upgrade() {
	post_install $1
}

pre_remove() {
	/bin/true
}

op=$1
shift

$op $*
